# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11
   
      - image: redislabs/redistimeseries:edge 
        command: ['--requirepass', 'SUPERSECRET']
        port: 6379:6379

    working_directory: /go/src/github.com/RedisLabs/redis-timeseries-go
    steps:
      - checkout   
      - run: go get -v -t -d ./...

      #run tests with coverage
      - run: go test -v -coverprofile=coverage.out
      - run: go tool cover -func=coverage.out
